In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import joblib

In [12]:
df = pd.read_excel("../data/raw/chad_csa_dataset_complete_44_variables.xlsx")
df.head()

,Year,Month,Region,ClimateZone,Rainfall_mm,MaxTemp_C,MinTemp_C,AvgTemp_C,RelativeHumidity_%,WindSpeed_mps,...,FarmSize_ha,CropYield_t_ha,Production_tons,LandUse,DroughtSeverity,DrySpell_days,FloodOccurrence,MarketPrice_CFAkg,PopulationDensity_km2,Elevation_m
0,2000,1,N'Djamena,Sahel,0.0,29.1,14.7,21.9,16.4,4.81,...,5.8,1.05,2712.5,Cropland,Mild,22,No,639.6,1200,298
1,2000,1,Abéché,Sahel,0.1,27.9,13.7,20.8,16.2,4.54,...,9.4,1.20,1260.7,Cropland,Mild,23,No,626.2,140,545
2,2000,1,Ati,Sahel,3.1,30.2,14.4,22.3,15.0,4.87,...,2.6,1.14,693.0,Cropland,Mild,25,No,657.6,60,294
3,2000,1,Mongo,Sahel,1.0,29.3,14.5,21.9,15.3,4.88,...,23.5,1.59,1053.5,Cropland,Mild,23,No,613.2,80,407
4,2000,1,Bongor,Sudanian,3.6,28.5,14.3,21.4,26.4,4.28,...,20.7,2.48,3668.7,Cropland,Mild,24,No,571.6,100,312

In [13]:
df.shape

(2400, 44)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   2400 non-null   int64
 1   Month                  2400 non-null   int64
 2   Region                 2400 non-null   object
 3   ClimateZone            2400 non-null   object
 4   Rainfall_mm            2400 non-null   float64
 5   MaxTemp_C              2400 non-null   float64
 6   MinTemp_C              2400 non-null   float64
 7   AvgTemp_C              2400 non-null   float64
 8   RelativeHumidity_%     2400 non-null   float64
 9   WindSpeed_mps          2400 non-null   float64
 10  SolarRadiation_MJ      2400 non-null   float64
 11  Evapotranspiration_mm  2400 non-null   float64
 12  SPI                    2400 non-null   float64
 13  SPEI                   2400 non-null   float64
 14  NDVI                   2400 non-null   float64
 15  EVI                    2400 non-null   float64
 16  LandSurfaceTemp_C      2400 non-null   float64
 17  SoilMoisture_%         2400 non-null   float64
 18  SoilTemperature_C      2400 non-null   float64
 19  SoilOrganicCarbon_%    2400 non-null   float64
 20  SoilPH                 2400 non-null   float64
 21  SoilTexture            2400 non-null   object
 22  SoilNitrogen_%         2400 non-null   float64
 23  SoilPhosphorus_mgkg    2400 non-null   float64
 24  SoilPotassium_mgkg     2400 non-null   float64
 25  BulkDensity_gcm3       2400 non-null   float64
 26  CropType               2400 non-null   object
 27  CropVariety            2400 non-null   object
 28  SowingMonth            2400 non-null   int64
 29  HarvestMonth           2400 non-null   int64
 30  GrowingSeason_days     2400 non-null   int64
 31  HarvestedArea_ha       2400 non-null   float64
 32  Irrigation_%           2400 non-null   float64
 33  Fertilizer_kg_ha       2400 non-null   float64
 34  FarmSize_ha            2400 non-null   float64
 35  CropYield_t_ha         2400 non-null   float64
 36  Production_tons        2400 non-null   float64
 37  LandUse                2400 non-null   object
 38  DroughtSeverity        1703 non-null   object
 39  DrySpell_days          2400 non-null   int64
 40  FloodOccurrence        2400 non-null   object
 41  MarketPrice_CFAkg      2400 non-null   float64
 42  PopulationDensity_km2  2400 non-null   int64
 43  Elevation_m            2400 non-null   int64
dtypes: float64(28), int64(8), object(8)
memory usage: 825.1+ KB

In [15]:
df.describe()

,Year,Month,Rainfall_mm,MaxTemp_C,MinTemp_C,AvgTemp_C,RelativeHumidity_%,WindSpeed_mps,SolarRadiation_MJ,Evapotranspiration_mm,...,HarvestedArea_ha,Irrigation_%,Fertilizer_kg_ha,FarmSize_ha,CropYield_t_ha,Production_tons,DrySpell_days,MarketPrice_CFAkg,PopulationDensity_km2,Elevation_m
count,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,...,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000
mean,2012.000000,6.500000,83.977083,33.121292,20.886958,27.004583,45.962833,4.213450,21.422000,5.928100,...,1562.233167,15.859208,45.264583,13.230083,2.025271,3160.944250,18.959167,578.642458,258.750000,387.000000
std,7.212605,3.452772,105.813767,3.751843,3.880905,3.633124,23.890226,0.563002,2.942732,1.544969,...,833.319899,5.549288,19.921070,6.913889,0.817768,2200.401781,7.178368,52.240823,359.394986,81.989639
min,2000.000000,1.000000,0.000000,26.400000,12.900000,19.700000,15.000000,3.000000,15.500000,2.000000,...,103.000000,0.000000,10.100000,1.000000,0.610000,98.800000,0.000000,411.400000,60.000000,294.000000
25%,2006.000000,3.750000,3.600000,30.275000,17.500000,24.500000,26.500000,3.760000,19.000000,5.010000,...,848.200000,12.775000,28.700000,7.375000,1.350000,1448.675000,15.000000,540.400000,87.500000,308.500000
50%,2012.000000,6.500000,33.250000,32.100000,21.700000,26.600000,39.000000,4.260000,21.300000,6.620000,...,1575.600000,17.600000,45.250000,13.500000,1.810000,2714.900000,22.000000,586.100000,120.000000,386.000000
75%,2018.000000,9.250000,151.525000,35.900000,23.700000,29.700000,67.300000,4.660000,23.500000,6.980000,...,2270.425000,19.900000,62.200000,19.200000,2.650000,4421.450000,24.000000,620.200000,190.000000,428.750000
max,2024.000000,12.000000,402.600000,42.600000,28.200000,34.800000,95.000000,5.400000,27.500000,7.810000,...,3000.000000,23.000000,80.000000,25.000000,4.420000,11791.600000,27.000000,682.900000,1200.000000,545.000000

In [16]:
df.isnull().sum()

Year                       0
Month                      0
Region                     0
ClimateZone                0
Rainfall_mm                0
MaxTemp_C                  0
MinTemp_C                  0
AvgTemp_C                  0
RelativeHumidity_%         0
WindSpeed_mps              0
SolarRadiation_MJ          0
Evapotranspiration_mm      0
SPI                        0
SPEI                       0
NDVI                       0
EVI                        0
LandSurfaceTemp_C          0
SoilMoisture_%             0
SoilTemperature_C          0
SoilOrganicCarbon_%        0
SoilPH                     0
SoilTexture                0
SoilNitrogen_%             0
SoilPhosphorus_mgkg        0
SoilPotassium_mgkg         0
BulkDensity_gcm3           0
CropType                   0
CropVariety                0
SowingMonth                0
HarvestMonth               0
GrowingSeason_days         0
HarvestedArea_ha           0
Irrigation_%               0
Fertilizer_kg_ha           0
FarmSize_ha                0
CropYield_t_ha             0
Production_tons            0
LandUse                    0
DroughtSeverity          697
DrySpell_days              0
FloodOccurrence            0
MarketPrice_CFAkg          0
PopulationDensity_km2      0
Elevation_m                0
dtype: int64